---
- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install apt common packages
  apt:
    name: "{{item}}"
  with_items:
    - apt-transport-https
    - python-apt
