---
- name: add nodesource apt key
  apt_key:
    url: >
      https://keyserver.ubuntu.com/pks/lookup?
      op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"

- name: add yarn apt key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: add repos
  apt_repository:
    repo: "{{item}}"
    update_cache: yes
  with_items:
    - deb https://deb.nodesource.com/node_{{node_version}} {{ansible_distribution_release}} main
    - deb https://dl.yarnpkg.com/debian/ stable main

- name: install nodejs and yarn pkg manager
  apt:
    name: "{{item}}"
  with_items:
  - nodejs
  - yarn
